In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
school = pd.read_csv("School_Attendance_by_Student_Group.csv")

In [3]:
school = school.drop(['2020-2021 student count','2020-2021 attendance rate','2019-2020 student count','2019-2020 attendance rate'], axis=1)

In [3]:
school.head()

,StoreId,uuid,createdAt,updatedAt,text,isAnonymous,reviewerId,replies,likeCount,isLiked,overall,restaurant_food,rider
0,aj85,001acc32-816b-41f3-9c25-7e23af4e414f,2023-09-24T13:58:30Z,2023-09-24T13:58:30Z,Chicken was pink. Did not eat and woukd not or...,False,kh5n9qpj,[],0,False,1,1,5.0
1,n964,00213503-ca54-448a-98d8-0a9cea483b9a,2024-01-21T13:30:20Z,2024-01-21T13:30:20Z,Nice,False,khoca0us,[],0,False,5,5,5.0
2,neo8,002b14a4-410d-48aa-91c4-e2b8a06166aa,2023-09-18T11:02:54Z,2023-09-18T11:02:54Z,ដាក់ត្រីខុស​,False,khlow9yx,[],0,False,1,1,NaN
3,mf6i,002f56fa-8a63-4abf-8035-7d7fb307f540,2024-01-22T08:20:45Z,2024-01-22T08:20:45Z,Love love love love it was so great,False,khve3tgq,[],0,False,4,4,2.0
4,t86n,0038f7b7-f76e-4cc6-af8c-ce43b57abb75,2023-08-16T03:45:44Z,2023-08-16T03:45:44Z,Didn't follow cooking instructions.\nIgnored r...,False,khxgmjrs,[],0,False,1,1,5.0

In [4]:
categories_count = school['Category'].value_counts()
plt.figure(figsize=(14,6))
plt.bar(categories_count.index, categories_count)
plt.title('Count plot of Category')
plt.xlabel('Category')
plt.ylabel('Count')
plt.show()

KeyError: 'Category'

In [6]:
school.sample(50)

,District code,District name,Category,Student group,2021-2022 student count - year to date,2021-2022 attendance rate - year to date,Reporting period,Date update
132,0150011,Bridgeport School District,Homelessness,Students Experiencing Homelessness,123,0.8455,June 2022,07/22/2022
1786,2640013,Integrated Day Charter School District,NaN,All Students,317,0.9341,June 2022,07/22/2022
1650,2150012,Regional School District 15,High Needs,Students With High Needs,930,0.9142,June 2022,07/22/2022
1740,2440014,Area Cooperative Educational Services,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,1052,0.8236,June 2022,07/22/2022
1727,2430014,Cooperative Educational Services,Free/Reduced Lunch,Reduced Price Meal Eligible,82,0.9141,June 2022,07/22/2022
1164,1310011,Southington School District,High Needs,Students With High Needs,2017,0.9180,June 2022,07/22/2022
602,0680011,Kent School District,High Needs,Students With High Needs,55,0.9244,June 2022,07/22/2022
978,1090011,Plainfield School District,Race/Ethnicity,All other races,89,0.8850,June 2022,07/22/2022
1931,2940013,Great Oaks Charter School District,English Learners,English Learners,71,0.9254,June 2022,07/22/2022
647,0740011,Litchfield School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,131,0.9122,June 2022,07/22/2022
1666,2170012,Regional School District 17,Free/Reduced Lunch,Reduced Price Meal Eligible,45,0.9436,June 2022,07/22/2022
1405,1560011,West Haven School District,High Needs,Students With High Needs,3832,0.9040,June 2022,07/22/2022
1803,2650013,Interdistrict School for Arts and Comm District,English Learners,English Learners,56,0.9245,June 2022,07/22/2022
310,0360011,Deep River School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,71,0.9470,June 2022,07/22/2022
289,0340011,Danbury School District,English Learners,English Learners,3541,0.9114,June 2022,07/22/2022
252,0300011,Columbia School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,90,0.9437,June 2022,07/22/2022
1270,1420011,Tolland School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,327,0.9119,June 2022,07/22/2022
31,0030011,Ashford School District,NaN,All Students,343,0.9309,June 2022,07/22/2022
1030,1140011,Preston School District,Race/Ethnicity,White,312,0.9126,June 2022,07/22/2022
428,0480011,Ellington School District,Race/Ethnicity,Black or African American,103,0.9255,June 2022,07/22/2022
917,1030011,Norwalk School District,Free/Reduced Lunch,Reduced Price Meal Eligible,1163,0.9155,June 2022,07/22/2022
1146,1290011,Somers School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,68,0.9322,June 2022,07/22/2022
706,0830011,Middletown School District,Homelessness,Students Experiencing Homelessness,35,0.8319,June 2022,07/22/2022
968,1080011,Oxford School District,Race/Ethnicity,Hispanic/Latino of any race,163,0.9301,June 2022,07/22/2022
1832,2700013,Side By Side Charter School District,Race/Ethnicity,Hispanic/Latino of any race,116,0.9454,June 2022,07/22/2022
1505,1660011,Wolcott School District,Free/Reduced Lunch,Free Meal Eligible,451,0.9306,June 2022,07/22/2022
145,0170011,Bristol School District,Homelessness,Students Experiencing Homelessness,65,0.8904,June 2022,07/22/2022
534,0590011,Groton School District,English Learners,English Learners,176,0.9117,June 2022,07/22/2022
949,1070011,Orange School District,Students With Disabilities,Students With Disabilities,110,0.9444,June 2022,07/22/2022
1609,2110012,Regional School District 11,High Needs,Students Without High Needs,88,0.9235,June 2022,07/22/2022
1234,1380011,Stratford School District,High Needs,Students Without High Needs,2714,0.9302,June 2022,07/22/2022
251,0300011,Columbia School District,Students With Disabilities,Students With Disabilities,43,0.9478,June 2022,07/22/2022
533,0590011,Groton School District,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,1997,0.8993,June 2022,07/22/2022
1947,2960013,Stamford Charter School for Excellence District,Students With Disabilities,Students With Disabilities,32,0.9246,June 2022,07/22/2022
146,0170011,Bristol School District,Students With Disabilities,Students With Disabilities,1417,0.9034,June 2022,07/22/2022
1980,9000016,Connecticut Technical Education and Career System,Free/Reduced Lunch,Free Meal Eligible,4181,0.8932,June 2022,07/22/2022
329,0390011,Eastford School District,Race/Ethnicity,White,106,0.9378,June 2022,07/22/2022
1395,1560011,West Haven School District,Students With Disabilities,Students With Disabilities,991,0.8936,June 2022,07/22/2022
1759,2450014,Learn,High Needs,Students With High Needs,602,0.8919,June 2022,07/22/2022
1275,1420011,Tolland School District,Race/Ethnicity,White,1803,0.9361,June 2022,07/22/2022
198,0230011,Canton School District,High Needs,Students Without High Needs,1018,0.9426,June 2022,07/22/2022
1825,2700013,Side By Side Charter School District,NaN,All Students,211,0.9459,June 2022,07/22/2022
1890,2880013,Achievement First Hartford Academy District,Students With Disabilities,Students With Disabilities,103,0.8641,June 2022,07/22/2022
2002,9020022,The Gilbert School District,NaN,All Students,421,0.8901,June 2022,07/22/2022
1624,2130012,Regional School District 13,Free/Reduced Lunch,Free/Reduced Price Meal Eligible,215,0.9071,June 2022,07/22/2022
1265,1410011,Thompson School District,High Needs,Students With High Needs,448,0.8713,June 2022,07/22/2022
205,0250011,Cheshire School District,NaN,All Students,4119,0.9466,June 2022,07/22/2022
1084,1220011,Salisbury School District,Students With Disabilities,Students With Disabilities,27,0.9160,June 2022,07/22/2022
1229,1380011,Stratford School District,English Learners,English Learners,487,0.9244,June 2022,07/22/2022
1095,1230011,Scotland School District,High Needs,Students With High Needs,46,0.9081,June 2022,07/22/2022

In [26]:
missing = school.isnull().sum()

In [8]:
totalCells = np.product(school.shape)

In [9]:
totalMissing = missing.sum()

In [10]:
missingPercent = (totalMissing/totalCells)*100

In [11]:
print("The dataset School_Attendance_by_Student_Group contains", round(missingPercent,2),"% missing values.")

The dataset School_Attendance_by_Student_Group contains 3.23 % missing values.